image_width: 1920
image_height: 1200
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [1458.67318,    0.     ,  957.96915,
            0.     , 1456.86263,  599.95146,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.157622, 0.109157, 0.000569, -0.000439, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [1384.23071,    0.     ,  956.38162,    0.     ,
            0.     , 1419.78809,  599.91236,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]
